source 'https://rubygems.org'

gem 'faraday'
gem 'roda'
gem 'tilt' # support Roda render plugin

group :test, :development do
  gem 'pry'
  gem 'rerun'
end

group :test do
  gem 'rspec'
  gem 'webmock'
end
